### PR TITLE
Removed the languages fields from the account settings

### PR DESCRIPTION
**Pull request by OmarIthawi**
Task:
- [Account settings: Both "Language" and "Preferred Language" should be removed](https://app.asana.com/0/96288420553298/96288420553298)

This is a re-open for #213 on master, after the dogwood branch have been merged.

### CODE REVIEW

**Comment by halawa** [comment]
@ahmedaljazzar , you mentioned in PR #213 that this may affect the mobile app. May you please take a look at the change in this PR (214) and tell if this still applies? Thanks!

**Comment by OmarIthawi** [comment]
Someone's reviewing my code 🎉

**Comment by halawa** [comment]
@ahmedaljazzar, do you think this PR is okay, from a mobile apps' perspective?

**Comment by ahmedaljazzar** [comment]
Yes it is :)

**Comment by halawa** [comment]
Thanks Ahmed! LGTM.

**Pull request merged**
