### PR TITLE
Added pacing to the enrollment API

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
### Description

TASK: No task assigned

I've just added the pacing to the API so we can use it in the apps.

### Notes
- Android App PR: [#40](https://github.com/Edraak/edraak-app-android/pull/40)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
Possible merge issues, but that's fine.

Feel free to merge if it passes QA.

**Comment by ahmedaljazzar** [comment]
@OmarIthawi, what are the possible merge issues?

**Comment by OmarIthawi** [comment]
@ahmedaljazzar One line conflict with future edX updates. A better solution would be is to include the pacing line within the other lines. This reduces the chances of having a merge conflict.

**Comment by OmarIthawi** [comment]
@ahmedaljazzar you can go ahead and merge this. I take my comments back.

**Comment by ahmedaljazzar** [comment]
Merging after QA and CR approval

**Pull request merged**
