### PR TITLE
Corrected RTL issues new forum post button

### PR DESCRIPTION
**Pull request by OmarIthawi**
- Float direction
 - Word break in Arabic on Google Chrome
 - Some HTML code reformat

**Task:**

 - [LMS/Discussion Component: The "منشور جديد" button is displayed improperly](https://app.asana.com/0/96288420553298/135577875276325)

### CODE REVIEW

**Comment by ahmedaljazzar** [comment]
Look how it looks like now: 
screen shot 2016-06-05 at 6 53 23 pm

**Comment by OmarIthawi** [comment]
Which browser @ahmedaljazzar ?

I've tested it on Chrome and it was totally fine!

**Comment by ahmedaljazzar** [comment]
Safari

**Comment by OmarIthawi** [comment]
👍

**Comment by OmarIthawi** [comment]
@ahmedaljazzar have you compiled the assets and everything?

**Comment by OmarIthawi** [comment]
BTW this is working fine in Safari, just compile the assets.


screen shot 2016-06-06 at 12 03 42 pm

**Comment by ahmedaljazzar** [comment]
انتا عندي بميرج يا عمر!

**Pull request merged**
