### PR TITLE
Sending non-sent message to Transifex.

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
Task: [Account setting: The "English" validation message is displaying for the "تغيير كلمة السر" under the account setting Arabic version ](https://app.asana.com/0/35717934599877/57005855510148/)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
:+1: 

@ahmedaljazzar looks good to me, I have two tiny requests: 
* Correct the indentation, it looks a bit odd!
* Push it on Transifex, again :)

**Comment by ahmedaljazzar** [comment]
@OmarIthawi Done.

**Comment by OmarIthawi** [comment]
@ahmedaljazzar

**Comment by OmarIthawi** [comment]
@ahmedaljazzar please prefix Edraak's branches with `edraak/`. This is good for `$ git branch | grep ^edraak` during search. It was @devalih idea, and I think it's good.

Anyway I'll merge this branch :).

**Comment by OmarIthawi** [comment]
:+1:

**Pull request merged**
