### PR TITLE
Prevent double `atomic` database locks, so the users can grade

### PR DESCRIPTION
**Pull request by OmarIthawi**
- See: https://openedx.atlassian.net/browse/TNL-3703

Tasks:

 - View the Certificate: https://app.asana.com/0/96288420553298/111493082538475
 - Download as PDF: https://app.asana.com/0/96288420553298/111493082538465

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@ahmedaljazzar حلمت فيها، وطلع عندي حل أفضل

خليني ارتب الوضع شوي

**Comment by OmarIthawi** [comment]
جاهزة مرة أخرى @ahmedaljazzar

**Comment by OmarIthawi** [comment]
Self merging so the QA can test.

**Comment by ahmedaljazzar** [comment]
@OmarIthawi, this is stated Merged, but I can find nothing in commits history :/

**Pull request merged**
