### PR TITLE
Removed the languages fields from the account settings

### PR DESCRIPTION
**Pull request by OmarIthawi**
Task:

 - [Account settings: Both "Language" and "Preferred Language" should be removed](https://app.asana.com/0/96288420553298/96288420553298)

### CODE REVIEW

**Comment by ahmedaljazzar** [comment]
This is may affect the mobile app @OmarIthawi, I need to check it their since we can build a logic their.

**Comment by OmarIthawi** [comment]
I can see, could you please provide a more concrete use case?

**Comment by OmarIthawi** [comment]
@ahmedaljazzar This only affect the web app. As far as the mobile app is concerned, this piece of JavaScript does not exist.

**Comment by OmarIthawi** [comment]
Closing to reopen to master.

**Comment by OmarIthawi** [comment]
Re-opened as #214.

**Pull request closed without merging**
