### PR TITLE
(WIP) Added the pre-requisite courses to the courses API

### PR DESCRIPTION
**Pull request by OmarIthawi**
**Task:**

 - [The Prerequisite section should be added under the "Marketing site and admin panel"](https://app.asana.com/0/23241728739082/81286093757843)

**Related PR:**

 - [Marketing Pull Request](https://bitbucket.org/Edraak/marketing-site/pull-requests/237/wip-prerequisite-courses/diff)

### CODE REVIEW

**Comment by ahmedaljazzar** [comment]
@OmarIthawi can you rebase it again on _edraak/edxsync-dogwood-feb-23_? There're another huge PR (#175) contains significant changes I could not ignore.

**Comment by OmarIthawi** [comment]
@ahmedaljazzar done :)

**Comment by ahmedaljazzar** [comment]
Can you contribute this to edX?

**Comment by ahmedaljazzar** [comment]
Simple, direct. Can you contribute this to edX?

**Comment by OmarIthawi** [comment]
[I guess so!](https://app.asana.com/0/23394127591909/135961275464216)

**Comment by OmarIthawi** [comment]
Changing this to a soft-prerequisite instead. Maybe we just don't need this!

**Comment by OmarIthawi** [comment]
Not needed anymore. Will not block the dogwood Edraak release.

**Pull request closed without merging**
