### PR TITLE
Fixing the untranslated Bayt.com strings verification email

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
### Description

Task: [Translation issues related to Bayt Verification email ](https://app.asana.com/0/35717934599877/65966205208571)

The translation was not pushed to Transfix because the i18n script did not see the string path. I could fix it in another way by including Bayt's path, but since we have a specific location for emails, I moved it there.

### Notes
- Example: Please review ASAP.
- Example: Feature is required for dogwood

### Testing
- [ ] i18n

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] Code review: @halawa 
- [ ] Code review: @OmarIthawi 
- [x] FYI @lbashayreh 

======
Update:

- You can find the string on Transfix [here](https://www.transifex.com/edraak/edraak/translate/#ar/$/94955734?q=Thank%20you%20for%20posting%20your%20certificate%20on%20Bayt.com)

### CODE REVIEW

**Comment by halawa** [comment]
Please review the filename to which you renamed the email template. Rename it to bayt_verification_email.txt, or fix the template name passed in `lms/djangoapps/edraak_bayt/views.py`

**Comment by ahmedaljazzar** [comment]
Updated

**Comment by halawa** [comment]
Looks good! :+1:

**Comment by ahmedaljazzar** [comment]
Looks like @OmarIthawi  is not available.

**Comment by halawa** [comment]
Yeah. But this fix is good to go. Unless you want to wait, I am fine merging.

**Comment by ahmedaljazzar** [comment]
Great, I'm ready to go. Thanks @halawa basha :)))

**Comment by halawa** [comment]
Anytime @ahmedaljazzar basha :) All thanks to you for your amazing and hard work!

**Pull request merged**
