### PR TITLE
Update discussion markdown editor add link and image modals

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
Fixes broken image issue.

Theme version: [a11c6ef](https://bitbucket.org/Edraak/edraak-2015-theme/commits/a11c6efa3596a5e322d1c6caec145f85459abf41?at=master)

Ref:
> PR #169 
> 
> Task: [ Broken image displays when the user add image to the Post, response, and comment text fields](https://app.asana.com/0/inbox/35717934599876/62550609502598/119311441260106)
> 
> Theme version:[Fixing image modal appearence.](https://bitbucket.org/Edraak/edraak-2015-theme/pull-requests/17/fixing-image-modal-appearence/diff)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
Task يا خوي

So I can test the issue and verify.

Otherwise, I can always do a blind merge 😆

**Comment by OmarIthawi** [comment]
Ahhh, that one!

OK I will check it out :)

**Comment by OmarIthawi** [comment]
I'll just merge blindly, it's already on master. So merging here makes things better or the same 😉

**Comment by ahmedaljazzar** [comment]
@OmarIthawi I think we need to close this since it's fixed in #169

**Comment by ahmedaljazzar** [comment]
Wow @OmarIthawi! I do not know if they are really the same, you know cherry picks usually coming with modifications 🎱

**Comment by OmarIthawi** [comment]
OK, I will test it quickly to see if it works fine.

**Comment by OmarIthawi** [comment]
It works Ahmad, check the screenshot below:

screen shot 2016-06-01 at 11 12 05 am

**Pull request merged**
