### PR TITLE
Do not force English transcript if no transcript has been found

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
### Description

TASK: [Video player: Caption icon should not be displayed for the video does'nt have a transcript ](https://app.asana.com/0/inbox/35717934599876/286559698961477/286808284353863)

edX are forcing the English language in the API, I guess it's a business need so I did comment them in our repo.

### Notes
- I didn't find the relative test cases to it, so if you feel this is important and you believe there's a test case, I can rewrite it for this specific edit.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
I'll pass this one. I'm really busy with other issues. Sorry.

**Comment by ahmedaljazzar** [comment]
> However, it would be nice if we add the two tests

I don't think it's a good idea to write new tests now for two reasons, I cannot test on Dogwood now, and there's no point from adding them as we are migrating to eucalyptus. I can apply our own tests for this feature during the feature picking later.

> I would add a check for settings.LANGUAGE_CODE == 'en', or a feature flag, this way this will survive future migrations

I see this is making it much complicated, this may increase the probability of code conflicts, plus it's not a feature to guard it behind a flag. The comment is straight forward, and I actually don't see where this could affect us later.

**Comment by Salomari1987** [comment]
@ahmedaljazzar, when applying the same change on Eucalyptus, I get failing tests as follows: https://build.edraakbeta.org/blue/organizations/jenkins/edraak%2Fedraak-platform/detail/PR-42/12/pipeline, worth looking at them just to make sure we are not breaking anything. This is important for documentation purposes. If you could just test it manually on the mobile_api to see if the returned JSON works as expected.

**Comment by ahmedaljazzar** [comment]
I don't see any reason why disabling subs could disable the volume button :/ Let me verify this tomorrow and see.

**Comment by ahmedaljazzar** [comment]
@Salomari1987: I just updated the PR, hope this is fixes the tests.

**Comment by ahmedaljazzar** [comment]
@Salomari1987: I just updated the PR, hope this is fixeing the tests.

**Comment by ahmedaljazzar** [comment]
I do believe now that hiding this feature behind a flag is important, I wonder if we should leave it to the next release so I can leverage `"LANGUAGE_CODE": "ar"` or not.

**Comment by ahmedaljazzar** [comment]
Salam @Salomari1987, please give me any feedback regarding this. I confirm that all failed tests on Eucalyptus are touching the transcripts expected default value that I'm changing in this PR.

**Comment by Salomari1987** [comment]
@ahmedaljazzar merging

**Comment by ahmedaljazzar** [comment]
gif-my-reaction-when-my-crush-finally-texts-me-back

**Pull request merged**
