### PR TITLE
Added logo for the ministry of education

### PR DESCRIPTION
**Pull request by OmarIthawi**
TASK: [MoE Logo](https://app.asana.com/0/64647197384459/351886661273858)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
Since it looks good. I'll merge, if there are any pending changes we'll open another one.

**Comment by ahmedaljazzar** [comment]
The change LGTM, although I didn't check it locally. So may be we need to deploy somewhere or have another review.

**Comment by ahmedaljazzar** [comment]
Raheem hahaha

**Comment by OmarIthawi** [comment]
> The change LGTM, although I didn't check it locally. So may be we need to deploy somewhere or have another review.

I'll need some @Edraak/quality-assurance  for this.

**Pull request merged**
