### PR TITLE
Get back the lost Arabic Math during dogwood release 

### PR DESCRIPTION
**Pull request by OmarIthawi**
This pull request is a part of a series of lost fixups during the dogwood merge. It is a breakdown of the closed PR #220:

> Due to the errors in the previous Dogwood pull request #161, some cypress updates were lost in the process. I'm reading them in this PR.
> 
> The affected pull requests are all the pull requests after #148 that has been merged into cypress (`master` or `edraak/core-changes`).
> 

----

 - **Ref:** #165 Include arabic.js MathJax extension `master`
 - **Head:** 3ac4be367c1f0eba2558dc274a6785c952f6c0d5
 - **Status:** Cherry-picked since some changes have been lost
 - **Task:** [Arabic MathJax does not work on Edraak Beta](https://app.asana.com/0/96288420553298/153283250712826)

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@ahmedaljazzar better?

**Comment by ahmedaljazzar** [comment]
It throws a server on the beta site. @OmarIthawi I think you need to a deep look why this is happening.

**Comment by OmarIthawi** [comment]
I think it's just a stupid out of space error. I tried deploying with the following command it it looks good to me:

    time ansible-playbook edraak/edxapp-quick.yml -i edraakbeta.org, -e@edraak/server-vars/edraakbeta.yml -e edx_platform_version=edraak/arabic-math-lost -e paver_assets=yes

**Comment by ahmedaljazzar** [comment]
Passed. Let's discuss this out of space issue later.

**Pull request merged**
