### PR TITLE
(WIP) Change the reset_password templates to mako templating

### PR DESCRIPTION
**Pull request by OmarIthawi**
Task:
- [The "Reset Password " page is implemented using the old theme](https://app.asana.com/0/96288420553298/51355945688720)

### CODE REVIEW

**Comment by ahmedaljazzar** [comment]
It throws: 

> ImportError at /password_reset_confirm/6ou6-4e5-3fe55eca312a31d66a82/
> No module named djangolib.markup

**Comment by OmarIthawi** [comment]
👍 will work on it.

**Comment by OmarIthawi** [comment]
It was a hectic cherry-pick, so something must have went wrong.

**Comment by OmarIthawi** [comment]
@ahmedaljazzar I'm unable to reproduce the error on my machine i.e. it works fine for me. May be it's environment specific. Let's test it on your machine.

**Comment by OmarIthawi** [comment]
@ahmedaljazzar added the magical file and now it works.

**Comment by OmarIthawi** [comment]
@ahmedaljazzar, I have decided with @halawa to postpone it and remove the footer in a bit in a later pull request, and get back to this after the dogwood release.

**Comment by ahmedaljazzar** [comment]
👍

**Comment by OmarIthawi** [comment]
Already included in eucalyptus: https://github.com/Edraak/edraak-platform

**Pull request closed without merging**
